version: '3.8'

networks:
  ft_mager:

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    networks:
      - ft_mager
  php:
    container_name: php
    build:
      context: ./deploy/php
    ports:
      - '9005:9000'
    volumes:
      - ./:/var/www/manager
    depends_on:
      - database
    networks:
      - ft_mager
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/manager
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - ft_mager
